#define SOFTWARE_RX_PIN 11
#define SOFTWARE_TX_PIN 12

#define RFID_RESET_PIN 13

#define SYMBOL_HEIGH 10
#define SYMBOL_WIDTH 6

#define TAG_NONE 0
#define TAG_FORWARD 1
#define TAG_BACKWARD 2
#define TAG_LEFT 3
#define TAG_RIGHT 4
#define TAG_REPEAT 5
#define TAG_AMOUNT 6

#define TAG_SEQUENCE 10

#define BUTTON_TAG_PIN 10
#define BUTTON_SET_PIN 9
#define BUTTON_PLAY_PIN 8

#define BUTTON_NONE 0
#define BUTTON_TAG 1
#define BUTTON_SET 2
#define BUTTON_PLAY 3

#define SETUP_PAUSE 1000
#define MENU_PAUSE 400
#define BUTTON_PAUSE 170

#define LCD_TAG_MENU 1*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_TAG_MEMO 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH

#define LCD_SEQUENCE_MENU 0*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_SEQUENCE_MEMO 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH
#define LCD_SEQUENCE_TAG 0*SYMBOL_WIDTH, 3*SYMBOL_HEIGH

#define LCD_PLAY_MENU 0*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_PLAY_SEQUENCE 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH

#define LCD_SEQUENCE_MENU 0*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_SEQUENCE_MEMO 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH
#define LCD_SEQUENCE_TAG 0*SYMBOL_WIDTH, 3*SYMBOL_HEIGH

#define LCD_MAIN_MENU_MEMO 0*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_MAIN_MENU_TAG 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH
#define LCD_MAIN_MENU_SET 0*SYMBOL_WIDTH, 3*SYMBOL_HEIGH
#define LCD_MAIN_MENU_PLAY 0*SYMBOL_WIDTH, 4*SYMBOL_HEIGH


