#define EEPROM_START_ADDRESS 100
#define TAG_LENGTH 12

#define RFID Serial3
#define BLUETOOTH Serial1

#define LEFT_MOTOR_PIN_A 7 
#define LEFT_MOTOR_PIN_B 8  
#define RIGHT_MOTOR_PIN_A 9   
#define RIGHT_MOTOR_PIN_B 10
#define RIGHT_MOTOR_PIN_ENABLE 11
#define LEFT_MOTOR_PIN_ENABLE 12

#define MOTOR_STOP 0
#define MOTOR_MAX_SPEED 255
#define MOTOR_MIN_SPEED 64

#define BUTTON_TAG_PIN 22
#define BUTTON_SET_PIN 24
#define BUTTON_PLAY_PIN 26
#define BUTTON_BLUETOOTH_PIN 28

#define FRONT_LIMIT_SWITCH 30
#define REAR_LIMIT_SWITCH 32


#define RFID_RESET_PIN 13

#define SYMBOL_HEIGH 10
#define SYMBOL_WIDTH 6

#define TAG_NONE ""
#define TAG_STOP 1
#define TAG_FORWARD 1
#define TAG_BACKWARD 2
#define TAG_LEFT 3
#define TAG_RIGHT 4
#define TAG_REPEAT 5
#define TAG_FORWARD_LEFT 6
#define TAG_FORWARD_RIGHT 7
#define TAG_BACKWARD_LEFT 8
#define TAG_BACKWARD_RIGHT 9
#define TAG_AMOUNT 10

#define TAG_SEQUENCE 10

#define BUTTON_NONE 0
#define BUTTON_TAG 1
#define BUTTON_SET 2
#define BUTTON_PLAY 3
#define BUTTON_BLUETOOTH 4

#define SETUP_PAUSE 1000
#define MENU_PAUSE 400
#define BUTTON_PAUSE 170

#define LCD_TAG_MENU 1*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_TAG_MEMO 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH

#define LCD_SEQUENCE_MENU 0*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_SEQUENCE_MEMO 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH
#define LCD_SEQUENCE_TAG 0*SYMBOL_WIDTH, 3*SYMBOL_HEIGH

#define LCD_PLAY_MENU 0*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_PLAY_SEQUENCE 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH

#define LCD_BLUETOOTH_MENU 0*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_BLUETOOTH_MEMO 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH

#define LCD_MAIN_MENU_MEMO 2*SYMBOL_WIDTH, 0*SYMBOL_HEIGH
#define LCD_MAIN_MENU_TAG 0*SYMBOL_WIDTH, 1*SYMBOL_HEIGH
#define LCD_MAIN_MENU_SET 0*SYMBOL_WIDTH, 2*SYMBOL_HEIGH
#define LCD_MAIN_MENU_PLAY 0*SYMBOL_WIDTH, 3*SYMBOL_HEIGH
#define LCD_MAIN_MENU_BLUETOOTH 0*SYMBOL_WIDTH, 4*SYMBOL_HEIGH


